### ISSUE TITLE
Exercise code isabsurd

### ISSUE THREAD

**Issue by VenkateshSrini** [petabridge/akka-bootcamp#251]
Hi
1) The code for filevalidator require two params in this lesson. But the props constructor takes only one
2) Ideally the order of creation should be Tail Actor, Tail coordinator actor, the only file validator actor

We cannot complete this exercise without competed code

**Comment by nathvi** [comment]
+1. I ran into the same problem. How is this been here since January?

**Comment by nathvi** [comment]
@VenkateshSrini , If you look at the FileValidatorActor class definition in **akka-bootcamp-master\akka-bootcamp-master\src\Unit-1\lesson4\Completed** you will see the correct definition. The documentation still needs to be updated to reflect this.

**Comment by Aaronontheweb** [comment]
I'm sorry, where exactly is this an issue? If you know what the issue is, please submit a pull request or link me to it.

**Comment by nathvi** [comment]
After the text:

"You'll also want to make sure to update the Props instance in Main that references the class:"

There is code:
`// Program.cs
Props validationActorProps = Props.Create(
  () => new FileValidatorActor(consoleWriterActor));`

This is inconsistent with the definition of FileValidatorActor.
Good documentation otherwise!

**Comment by nathvi** [comment]
#254 is the pull request I made to hopefully get this order corrected.

**Comment by nathvi** [comment]
This should be closed now.

**Comment by izavala** [comment]
https://github.com/petabridge/akka-bootcamp/pull/254
