### ISSUE TITLE
Lession 5 dead letters

### ISSUE THREAD

**Issue by alistair** [petabridge/akka-bootcamp#50]
I'm running using mono on linux and seem to be getting a deadletter error.  This occurs on both the solution I modified as well as the completed solution you provide.

This is what I get

    Please provide the URI of a log file on disk.
    
    file.log
    [INFO][12/03/2015 10:43:41 p.m.][Thread 0005][akka://MyActorSystem/deadLetters] Message String from akka://MyActorSystem/user/consoleReaderActor to akka://MyActorSystem/deadLetters was not delivered. 1 dead letters encountered.

**Comment by kjellski** [comment]
I had that too on Windows 8.1 - VS2013. Wasn't sure if it was only my problem. Thanks for reporting anyways...

**Comment by Aaronontheweb** [comment]
so I took a look at this - here's the area where the code may or may not work for you in the `/Completed/` section:

https://github.com/petabridge/akka-bootcamp/blob/master/src/Unit-1/lesson5/Completed/ConsoleReaderActor.cs#L48

```csharp
// otherwise, just send the message off for validation
Context.ActorSelection("/user/validationActor").Tell(message);
```

Some possible issues here might be:

* the URL bug that still affects Mono users on Akka.NET v0.8 - this is fixed in the next release of Akka.NET
* Not properly capitalizing the name in the path

Here's a workaround - we can try specifying the absolute URI of the actor in our `ActorSelection`:

```csharp
Context.ActorSelection("akka://MyActorSystem/user/validationActor").Tell(message);
```

Does that help?

**Comment by alistair** [comment]
Hi @Aaronontheweb sorry for taking so long to respond

Yes this change and also updating FileValidationActor to the following fixed the issue

    // start coordinator
    Context.ActorSelection("akka://MyActorSystem/user/tailCoordinatorActor").Tell(new TailCoordinatorActor.StartTail(msg, _consoleWriterActor));

Thanks
