### ISSUE TITLE
[Unit 1 Lesson 4] TailActor never closes the file stream

### ISSUE THREAD

**Issue by etishor** [petabridge/akka-bootcamp#58]
In [TailActor.cs](https://github.com/petabridge/akka-bootcamp/blob/master/src/Unit-1/lesson4/Completed/TailActor.cs) the actor opens and holds a Stream pointing to the input file. The actor never closes the stream or associated stream reader. 

This is probably not an issue in this particular case, since the stream is supposed to be opened for the duration of the app but since this is lesson material it might be a good idea to clarify such use cases. Or maybe show how to control the lifetime of the actor & stream.  

Nevertheless this raises a few questions: 

Should actors own disposable resources? If yes when are these resources supposed to be released?

Assuming an app needs to open and close multiple files what is the best way to ensure no resources are leaked? 

Is the general recommendation to avoid controlling resource lifetime with messages (for ex to have a message to open the file and a message to close the file) and instead have the resource operation inside a message handler ( on receive ReadFromFile message - open file, read content, close file - pass content to other actor ).?

Thanks, and btw awesome idea with the akka bootcamp.

**Comment by Aaronontheweb** [comment]
These are good questions!

> Should actors own disposable resources? If yes when are these resources supposed to be released?

Yes, they should! And *when* should actors dispose their own resources? It depends :p 

If you take a look at the [`PerformanceCounterActor` in Unit 2](https://github.com/petabridge/akka-bootcamp/blob/master/src/Unit-2/lesson3/Completed/Actors/PerformanceCounterActor.cs#L39) you can see that we release the `IDisposable` resources that actor uses inside the `PostStop` method, which gets called whenever the actor stops or restarts.

However, let's say your actor has to use a single instance of an IDisposable method (like a database context object) in order to respond to a message... Well in that case you'd probably just want to use a `using` statement right there inside the actor.

So it really depends on the lifecycle of the actor - in Unit 1 the actor holds onto the stream indefinitely until it's shut down, because that's just how `tail` works. However, if you have a long-lived actor that's trying to hold onto a short-lived disposable resource (like a network connection) then you might need to regularly dispose and re-acquire copies of that resource again.

Controlling resource allocation with control messages is a perfectly fine strategy - I've done it before using scheduled messages.

**Comment by etishor** [comment]
Thanks for the response. I think I still don't have a clear picture on how the lifespan of an actor is defined and how the lifecycle is controlled. I'm sure that will change as I go on with the lessons. Btw awesome idea with sending one lesson by email each day - not to much, not to little- just perfect :)

For now I'll stick to this mental model: If the lifetime of the resource matches the lifetime of the actor than it is no problem for the actor to hold a reference and dispose if when it stops/restarts. If the lifetimes are different then the resource should be created and disposed inside the processing of a message. 

Thanks and feel free to close this issue. I'll create a new issue if things are still not clear after a few more lessons.
